[package]
name = "rhiza"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.26", features = ["derive"] }
colored = "3.0.0"
inquire = "0.7.5"
shellexpand = "3.1.0"
walkdir = "2.5.0"
winapi = "0.3.9"
winreg = "0.55.0"
